# @package data_loader
_target_: src.dataset.BSRSC.get_data_loaders
train_dir: /mnt/petrelfs/share_data/qudelin/RS/BS-RSC/train
val_dir: /mnt/petrelfs/share_data/qudelin/RS/BS-RSC/val
test_dir: /mnt/petrelfs/share_data/qudelin/RS/BS-RSC/test
batch_size: ${batch_size}
training: true
seq_len: ${arch.n_inputs}
shuffle: true
num_workers: ${n_cpu}

data_aug: 
  _target_: src.dataset.transforms.ToTensor