# @package data_loader
_target_: src.dataset.Carla.get_data_loaders
train_dir: /mnt/petrelfs/share_data/qudelin/RS/Carla/train
val_dir: /mnt/petrelfs/share_data/qudelin/RS/Carla/val
test_dir: /mnt/petrelfs/share_data/qudelin/RS/Carla/test
batch_size: 1
seq_len: ${arch.n_inputs}
load_mask: true
training: false
shuffle: false
num_workers: 4
load_middle_gs: true

data_aug: 
  _target_: src.dataset.transforms.ToTensor