# @package data_loader
_target_: src.dataset.Fastec.get_data_loaders
train_dir: /mnt/petrelfs/share_data/qudelin/RS/Fastec/train
val_dir: /mnt/petrelfs/share_data/qudelin/RS/Fastec/val
test_dir: /mnt/petrelfs/share_data/qudelin/RS/Fastec/test
batch_size: 1
seq_len: ${arch.n_inputs}
training: false
shuffle: false
num_workers: 4
load_middle_gs: true

data_aug: 
  _target_: src.dataset.transforms.ToTensor