# @package _global_
name: QRST_GMA

arch:
  _target_: src.model.model.QRST
  n_inputs: 5
  joinType: concat
  ks: 5
  dilation: 1
  nf: [192, 128, 64, 32]
  config_file: ~/.cache/mim/gma_plus-p_8x2_120k_mixed_368x768.py
  checkpoint_file: ~/.cache/mim/gma_plus-p_8x2_120k_mixed_368x768.pth
